---
title: "index"
author: "Brendan Lehman"
date: "November 30, 2017"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Scatterplot

```{r scatterplot}

# data()
# ?mpg
# mpg
ggplot(data = mpg, aes(x = displ, y = hwy)) +
  geom_point()
```

### I need `color`!

```{r color}
ggplot(data = mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point()
```

### `shape`: need a b&w figure

Changed 'color' to shape

```{r b&w}
ggplot(data = mpg, aes(x = displ, y = hwy, shape = class)) +
  geom_point()
```

### `size` and  `color`

```{r scatter shape color}
ggplot(data = mpg, aes(x = cty, y = hwy, size = class)) +
  geom_point(alpha=0.2, color ="blue")
```


## Boxplot


##Exercise

```{r exercise}
ggplot(data = mpg) + 
      geom_point(aes(x = displ, y = hwy, color = "blue"))

```


## Geoms

```{r geom_examples}

ggplot(mpg, aes(x=drv, y=hwy)) +
  geom_violin()

```


## Multiple geoms

```{r mult_geoms}

ggplot(data = mpg) +
  geom_point(aes(x=displ, y=hwy)) +
  geom_smooth(aes(x=displ, y=hwy))


ggplot(data=mpg, aes(x=displ, y=hwy)) +
  geom_point() +
  geom_smooth()



```


## Customization

```{r custom}

ggplot(data = mpg) +
  geom_point(aes(x=displ, y=hwy)) +
  geom_smooth(aes(x=displ, y=hwy))


ggplot(data=mpg, aes(x=displ, y=hwy)) +
  geom_point() +
  geom_smooth() +
  labs(title ="Relationship b/w engine size and mpg",
       x = "engine disp",
       y = "highway mpg") +
  theme_bw() +
  theme(text = element_text(size = 16))


```

## My plot

```{r car categories}

ggplot(data=mpg, aes(x=year, y=displ)) +
  geom_point()

```




## Data Wrangling with `dplyr`

```{preamble}

gapminder <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

gapminder

## useful functions to get to know your data
head(gapminder, 30)

str(gapminder)

## column headers
names(gapminder)

dim(gapminder)
ncol(gapminder)

# combine with c()
c(nrow(gapminder), ncol(gapminder))

summary(gapminder)

## look at just single column
```

## actually working with dplyr

```{working with dplyr}

filter(gapminder, lifeExp < 29)

mean(filter(gapminder, country == "Sweden")$lifeExp)

##pipe operator `%>%`

gapminder %>% head()


gapminder %>% 
  filter(country == "Sweden") %>% 
  summarize(mean(lifeExp))




```

## select by columns

```{data manip by column}

select(gapminder, year, lifeExp)

gapminder %>%
  select(year, lifeExp) %>% 
  tail()

## combine what we've learned

gapminder %>% 
  filter(country == "Cambodia") %>% 
  select(country, year, pop, gdpPercap)


gapminder %>% 
  filter(country == "Cambodia") %>% 
  select(-continent, -lifeExp)

## a few more things with filter
gapminder %>% 
  filter(country == "Mexico", year == 2002)

## mutate() to add columns

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

## let's add an index
gapminder %>% 
  mutate(index = 1:nrow(gapminder))


gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  mutate(max_gdp_cap = max(gdpPercap))

##group_by() so that we can get 2 maxes
gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  group_by(country) %>% 
  summarize(max_gdpPercap = max(gdpPercap))

##for all countries
gapminder %>% 
  group_by(country) %>% 
  summarize(max_gdpPercap = max(gdpPercap))

##let's keep the year associated with tat max_dgp
l <- gapminder %>% 
  group_by(country) %>% 
  mutate(max_gdpPercap = max(gdpPercap)) %>% 
  filter(max_gdpPercap == gdpPercap)



```

## joining datasets

```{joining datasets}
# read in co2 data
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")


co2 %>% head()

gap_2007 <- gapminder %>% 
  filter(year == 2007)

#left_join gap 2007
lj <- left_join(gap_2007, co2, by = "country")

## right join gap 2007 to co2

rj <- right_join(gap_2007, co2)
rj %>%  dim()

```



